# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_environment.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="agent_environment.proto",
    package="aea.gdp8.agent_environment_communication.v0_1_0",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x17\x61gent_environment.proto\x12/aea.gdp8.agent_environment_communication.v0_1_0"\xa3\x05\n\x17\x41gentEnvironmentMessage\x12n\n\x06\x61\x63tion\x18\x05 \x01(\x0b\x32\\.aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Action_PerformativeH\x00\x12j\n\x04tick\x18\x06 \x01(\x0b\x32Z.aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Tick_PerformativeH\x00\x1a\xb3\x01\n\x07\x43ommand\x12m\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\\.aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Command.CommandEnum"9\n\x0b\x43ommandEnum\x12\x07\n\x03NOP\x10\x00\x12\x0e\n\nSEND_WATER\x10\x01\x12\x11\n\rRECEIVE_WATER\x10\x02\x1aS\n\x11Tick_Performative\x12\x12\n\ntile_water\x18\x01 \x01(\x05\x12\x13\n\x0b\x61gent_water\x18\x02 \x01(\x05\x12\x15\n\rneighbour_ids\x18\x03 \x03(\x05\x1a\x90\x01\n\x13\x41\x63tion_Performative\x12\x61\n\x07\x63ommand\x18\x01 \x01(\x0b\x32P.aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Command\x12\x16\n\x0ewater_quantity\x18\x02 \x01(\x05\x42\x0e\n\x0cperformativeb\x06proto3',
)


_AGENTENVIRONMENTMESSAGE_COMMAND_COMMANDENUM = _descriptor.EnumDescriptor(
    name="CommandEnum",
    full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Command.CommandEnum",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="NOP", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="SEND_WATER", index=1, number=1, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="RECEIVE_WATER", index=2, number=2, serialized_options=None, type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=447,
    serialized_end=504,
)
_sym_db.RegisterEnumDescriptor(_AGENTENVIRONMENTMESSAGE_COMMAND_COMMANDENUM)


_AGENTENVIRONMENTMESSAGE_COMMAND = _descriptor.Descriptor(
    name="Command",
    full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Command",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="command",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Command.command",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _AGENTENVIRONMENTMESSAGE_COMMAND_COMMANDENUM,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=325,
    serialized_end=504,
)

_AGENTENVIRONMENTMESSAGE_TICK_PERFORMATIVE = _descriptor.Descriptor(
    name="Tick_Performative",
    full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Tick_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="tile_water",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Tick_Performative.tile_water",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="agent_water",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Tick_Performative.agent_water",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="neighbour_ids",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Tick_Performative.neighbour_ids",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=506,
    serialized_end=589,
)

_AGENTENVIRONMENTMESSAGE_ACTION_PERFORMATIVE = _descriptor.Descriptor(
    name="Action_Performative",
    full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Action_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="command",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Action_Performative.command",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="water_quantity",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Action_Performative.water_quantity",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=592,
    serialized_end=736,
)

_AGENTENVIRONMENTMESSAGE = _descriptor.Descriptor(
    name="AgentEnvironmentMessage",
    full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="action",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.action",
            index=0,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="tick",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.tick",
            index=1,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _AGENTENVIRONMENTMESSAGE_COMMAND,
        _AGENTENVIRONMENTMESSAGE_TICK_PERFORMATIVE,
        _AGENTENVIRONMENTMESSAGE_ACTION_PERFORMATIVE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="performative",
            full_name="aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.performative",
            index=0,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=77,
    serialized_end=752,
)

_AGENTENVIRONMENTMESSAGE_COMMAND.fields_by_name[
    "command"
].enum_type = _AGENTENVIRONMENTMESSAGE_COMMAND_COMMANDENUM
_AGENTENVIRONMENTMESSAGE_COMMAND.containing_type = _AGENTENVIRONMENTMESSAGE
_AGENTENVIRONMENTMESSAGE_COMMAND_COMMANDENUM.containing_type = (
    _AGENTENVIRONMENTMESSAGE_COMMAND
)
_AGENTENVIRONMENTMESSAGE_TICK_PERFORMATIVE.containing_type = _AGENTENVIRONMENTMESSAGE
_AGENTENVIRONMENTMESSAGE_ACTION_PERFORMATIVE.fields_by_name[
    "command"
].message_type = _AGENTENVIRONMENTMESSAGE_COMMAND
_AGENTENVIRONMENTMESSAGE_ACTION_PERFORMATIVE.containing_type = _AGENTENVIRONMENTMESSAGE
_AGENTENVIRONMENTMESSAGE.fields_by_name[
    "action"
].message_type = _AGENTENVIRONMENTMESSAGE_ACTION_PERFORMATIVE
_AGENTENVIRONMENTMESSAGE.fields_by_name[
    "tick"
].message_type = _AGENTENVIRONMENTMESSAGE_TICK_PERFORMATIVE
_AGENTENVIRONMENTMESSAGE.oneofs_by_name["performative"].fields.append(
    _AGENTENVIRONMENTMESSAGE.fields_by_name["action"]
)
_AGENTENVIRONMENTMESSAGE.fields_by_name[
    "action"
].containing_oneof = _AGENTENVIRONMENTMESSAGE.oneofs_by_name["performative"]
_AGENTENVIRONMENTMESSAGE.oneofs_by_name["performative"].fields.append(
    _AGENTENVIRONMENTMESSAGE.fields_by_name["tick"]
)
_AGENTENVIRONMENTMESSAGE.fields_by_name[
    "tick"
].containing_oneof = _AGENTENVIRONMENTMESSAGE.oneofs_by_name["performative"]
DESCRIPTOR.message_types_by_name["AgentEnvironmentMessage"] = _AGENTENVIRONMENTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentEnvironmentMessage = _reflection.GeneratedProtocolMessageType(
    "AgentEnvironmentMessage",
    (_message.Message,),
    {
        "Command": _reflection.GeneratedProtocolMessageType(
            "Command",
            (_message.Message,),
            {
                "DESCRIPTOR": _AGENTENVIRONMENTMESSAGE_COMMAND,
                "__module__": "agent_environment_pb2"
                # @@protoc_insertion_point(class_scope:aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Command)
            },
        ),
        "Tick_Performative": _reflection.GeneratedProtocolMessageType(
            "Tick_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _AGENTENVIRONMENTMESSAGE_TICK_PERFORMATIVE,
                "__module__": "agent_environment_pb2"
                # @@protoc_insertion_point(class_scope:aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Tick_Performative)
            },
        ),
        "Action_Performative": _reflection.GeneratedProtocolMessageType(
            "Action_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _AGENTENVIRONMENTMESSAGE_ACTION_PERFORMATIVE,
                "__module__": "agent_environment_pb2"
                # @@protoc_insertion_point(class_scope:aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage.Action_Performative)
            },
        ),
        "DESCRIPTOR": _AGENTENVIRONMENTMESSAGE,
        "__module__": "agent_environment_pb2"
        # @@protoc_insertion_point(class_scope:aea.gdp8.agent_environment_communication.v0_1_0.AgentEnvironmentMessage)
    },
)
_sym_db.RegisterMessage(AgentEnvironmentMessage)
_sym_db.RegisterMessage(AgentEnvironmentMessage.Command)
_sym_db.RegisterMessage(AgentEnvironmentMessage.Tick_Performative)
_sym_db.RegisterMessage(AgentEnvironmentMessage.Action_Performative)


# @@protoc_insertion_point(module_scope)
