agent_name: agent_aea
author: gdp8
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=0.11.0, <=1.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols:
- gdp8/agent_agent:0.1.0
- gdp8/agent_environment:0.1.0
- gdp8/default:0.13.0
skills:
- gdp8/Action_Each_Turn:0.1.0
default_ledger: fetchai
required_ledgers: []
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai: {}
default_connection: null
