agent_name: agent_aea
author: gdp8
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.0.1'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/p2p_libp2p_client:0.18.0
contracts: []
protocols:
- fetchai/default:1.0.0
- fetchai/signing:1.0.0
- fetchai/state_update:1.0.0
- gdp8/agent_agent:0.1.0
- gdp8/agent_environment:0.1.0
skills:
- gdp8/agent_action_each_turn:0.1.0
default_ledger: fetchai
required_ledgers:
- fetchai
default_routing: {}
connection_private_key_paths:
  fetchai: ckp.txt
private_key_paths:
  fetchai: fetchai_private_key.txt
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai: {}
default_connection: fetchai/p2p_libp2p_client:0.18.0
