# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_agent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="agent_agent.proto",
    package="aea.gdp8.agent_agent_communication.v0_1_0",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x11\x61gent_agent.proto\x12)aea.gdp8.agent_agent_communication.v0_1_0"\xfe\x02\n\x11\x41gentAgentMessage\x12r\n\x0ereceiver_reply\x18\x05 \x01(\x0b\x32X.aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Receiver_Reply_PerformativeH\x00\x12r\n\x0esender_request\x18\x06 \x01(\x0b\x32X.aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Sender_Request_PerformativeH\x00\x1a\x43\n\x1bSender_Request_Performative\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x13\n\x0bturn_number\x18\x02 \x01(\x05\x1a,\n\x1bReceiver_Reply_Performative\x12\r\n\x05reply\x18\x01 \x01(\tB\x0e\n\x0cperformativeb\x06proto3',
)


_AGENTAGENTMESSAGE_SENDER_REQUEST_PERFORMATIVE = _descriptor.Descriptor(
    name="Sender_Request_Performative",
    full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Sender_Request_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="request",
            full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Sender_Request_Performative.request",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="turn_number",
            full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Sender_Request_Performative.turn_number",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=318,
    serialized_end=385,
)

_AGENTAGENTMESSAGE_RECEIVER_REPLY_PERFORMATIVE = _descriptor.Descriptor(
    name="Receiver_Reply_Performative",
    full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Receiver_Reply_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="reply",
            full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Receiver_Reply_Performative.reply",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=387,
    serialized_end=431,
)

_AGENTAGENTMESSAGE = _descriptor.Descriptor(
    name="AgentAgentMessage",
    full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="receiver_reply",
            full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.receiver_reply",
            index=0,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="sender_request",
            full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.sender_request",
            index=1,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _AGENTAGENTMESSAGE_SENDER_REQUEST_PERFORMATIVE,
        _AGENTAGENTMESSAGE_RECEIVER_REPLY_PERFORMATIVE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="performative",
            full_name="aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.performative",
            index=0,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=65,
    serialized_end=447,
)

_AGENTAGENTMESSAGE_SENDER_REQUEST_PERFORMATIVE.containing_type = _AGENTAGENTMESSAGE
_AGENTAGENTMESSAGE_RECEIVER_REPLY_PERFORMATIVE.containing_type = _AGENTAGENTMESSAGE
_AGENTAGENTMESSAGE.fields_by_name[
    "receiver_reply"
].message_type = _AGENTAGENTMESSAGE_RECEIVER_REPLY_PERFORMATIVE
_AGENTAGENTMESSAGE.fields_by_name[
    "sender_request"
].message_type = _AGENTAGENTMESSAGE_SENDER_REQUEST_PERFORMATIVE
_AGENTAGENTMESSAGE.oneofs_by_name["performative"].fields.append(
    _AGENTAGENTMESSAGE.fields_by_name["receiver_reply"]
)
_AGENTAGENTMESSAGE.fields_by_name[
    "receiver_reply"
].containing_oneof = _AGENTAGENTMESSAGE.oneofs_by_name["performative"]
_AGENTAGENTMESSAGE.oneofs_by_name["performative"].fields.append(
    _AGENTAGENTMESSAGE.fields_by_name["sender_request"]
)
_AGENTAGENTMESSAGE.fields_by_name[
    "sender_request"
].containing_oneof = _AGENTAGENTMESSAGE.oneofs_by_name["performative"]
DESCRIPTOR.message_types_by_name["AgentAgentMessage"] = _AGENTAGENTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentAgentMessage = _reflection.GeneratedProtocolMessageType(
    "AgentAgentMessage",
    (_message.Message,),
    {
        "Sender_Request_Performative": _reflection.GeneratedProtocolMessageType(
            "Sender_Request_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _AGENTAGENTMESSAGE_SENDER_REQUEST_PERFORMATIVE,
                "__module__": "agent_agent_pb2"
                # @@protoc_insertion_point(class_scope:aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Sender_Request_Performative)
            },
        ),
        "Receiver_Reply_Performative": _reflection.GeneratedProtocolMessageType(
            "Receiver_Reply_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _AGENTAGENTMESSAGE_RECEIVER_REPLY_PERFORMATIVE,
                "__module__": "agent_agent_pb2"
                # @@protoc_insertion_point(class_scope:aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage.Receiver_Reply_Performative)
            },
        ),
        "DESCRIPTOR": _AGENTAGENTMESSAGE,
        "__module__": "agent_agent_pb2"
        # @@protoc_insertion_point(class_scope:aea.gdp8.agent_agent_communication.v0_1_0.AgentAgentMessage)
    },
)
_sym_db.RegisterMessage(AgentAgentMessage)
_sym_db.RegisterMessage(AgentAgentMessage.Sender_Request_Performative)
_sym_db.RegisterMessage(AgentAgentMessage.Receiver_Reply_Performative)


# @@protoc_insertion_point(module_scope)
